version: 2
jobs:
  py36:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - restore_cache:
          keys:
            - py36-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip3 install tox
            tox -e py36 --notest

      - save_cache:
          paths:
            - ./venv
            - .tox/py36
          key: py36-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}

      - run:
          name: run tests
          command: |
            source venv/bin/activate
            tox -e py36

  py27:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout

      - restore_cache:
          keys:
            - py27-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install tox
            tox -e py27 --notest

      - save_cache:
          paths:
            - ./venv
            - .tox/py27
          key: py27-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}

      - run:
          name: run tests
          command: |
            source venv/bin/activate
            tox -e py27

  pypi:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Upload to PyPI
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install twine wheel
            python setup.py sdist bdist_wheel
            twine upload dist/*

workflows:
  version: 2
  unittest:
    jobs:
      - py27
      - py36
      - pypi:
          requires:
            - py27
            - py36
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/
